### ISSUE TITLE
Character conversion error when installing

### ISSUE THREAD

**Issue by electrum** [jordansissel/ruby-sshkeyauth#2]
I get a character conversion error when installing using Ruby 1.9.2 on OS X:

```
$ ruby --version
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]
$ gem --version
1.6.2

$ gem install sshkeyauth
Fetching: net-ssh-2.2.1.gem (100%)
Fetching: sshkeyauth-0.0.11.gem (100%)
Successfully installed net-ssh-2.2.1
Successfully installed sshkeyauth-0.0.11
2 gems installed
Installing ri documentation for net-ssh-2.2.1...
unable to convert "\xE7" from ASCII-8BIT to UTF-8 for lib/net/ssh/authentication/pageant.rb, skipping
Installing ri documentation for sshkeyauth-0.0.11...
Installing RDoc documentation for net-ssh-2.2.1...
unable to convert "\xE7" from ASCII-8BIT to UTF-8 for lib/net/ssh/authentication/pageant.rb, skipping
Installing RDoc documentation for sshkeyauth-0.0.11...

```

**Comment by jordansissel** [comment]
That looks like an eror in Net-SSH, not this project. You can contact the net-ssh folks here:

https://github.com/net-ssh/net-ssh

As a side note, I don't think this error means much. It happened while gem was trying to build the docs for you, which you may not even read locally. You can the net-ssh read docs on rubydoc.info and here http://net-ssh.github.com/net-ssh/
Additionally, the error is in generating documentation which you can read online at rubydoc.info anyway. 

Hope this helps :)

**Comment by electrum** [comment]
Sorry, I didn't read the error close enough to see it's from net-ssh.  Thanks for the very helpful response :)
