### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by bobtfish** [jordansissel/ruby-sshkeyauth#3]
Hiya.

There is no license info for this code, which makes it hard for me to reuse in a commercial setting.

Can you please commit a license to the dist in the README or the gemspec?

Thanks in advance!

**Comment by traylenator** [comment]
+1  I'd like to add this package to Fedora.

**Comment by jordansissel** [comment]
Done!

**Comment by bobtfish** [comment]
:+1: thanks!

**Comment by traylenator** [comment]
Thanks, totally missed this 4 years ago.
